group_imports = "StdExternalCrate"
edition = "2024"                   # keep this in sync with Cargo.toml
condense_wildcard_suffixes = true
doc_comment_code_block_width = 100
enum_discrim_align_threshold = 60
force_explicit_abi = false
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hard_tabs = false
indent_style = "Block"
hex_literal_case = "Upper"
imports_granularity = "Crate"
imports_layout = "Vertical"
inline_attribute_width = 60
match_block_trailing_comma = true
max_width = 110
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
struct_field_align_threshold = 60
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
