name: "Build NH"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build-linux:
    name: "Build NH on Linux"
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@master
        with:
          github_access_token: ${{ github.token }}

      - uses: actions/checkout@v7

      - run: nix build -L --no-link
        name: Build

  build-darwin:
    name: "Build NH on Darwin"
    runs-on: macos-latest

    steps:
      - uses: cachix/install-nix-action@master
        with:
          github_access_token: ${{ github.token }}

      - uses: actions/checkout@v7

      - name: Build NH with Nix
        run: nix build -L --no-link
