name: "Check formatting & lints"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  treewide-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ github.token }}

      - name: Checking Code (format, lints, etc.)
        run: |
          eval "$(nix print-dev-env)"
          just check || exit 1
